<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.0.0</Version>
    <OutputType>exe</OutputType>
    <Company>Froststrap</Company>
    <Description>Generation of icons tooling</Description>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1416;CA2007</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SvgConverter.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
</Project>

