<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>ColorPicker</RootNamespace>
    <IsPackable>false</IsPackable>

    <Authors>Egor Mozgovoy, Krzysztof Krysiński</Authors>
    <Company>PixiEditor</Company>
    <Copyright>PixiEditor</Copyright>
    <Version>1.0.10</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.0.5" />
    <PackageReference Include="Xaml.Behaviors" Version="12.0.0.1" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Images\**" />
  </ItemGroup>
</Project>
