[package]
name = "virtualdisplay"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
objc2.workspace = true
block2.workspace = true
dispatch2.workspace = true
objc2-core-graphics.workspace = true
objc2-core-foundation.workspace = true
